### ISSUE TITLE
폴더구조 "leetcode - 994.RottingOranges.js" 이런식으로 해야할까?

### ISSUE THREAD

**Issue by Hong-been** [zzzzsb/2022-Algorithm-Study#17]
폴더구조에서 "leetcode - 994.RottingOranges.js" 이런식으로 해야할까?

1. "leetcode" 디렉토리명 괜츈??

2. 셋중에 함 봐바(난 2번이 젤 난거같오)
   1. "994.js" 로만 하기엔 문제가 뭔지모르고
   2. "994.RottingOranges.js" 를 다 쓰면 좀 길긴해,, 
   3. "RottingOranges.js" 이러면 나중에 문제찾기 어려우려나?

**Comment by zzzzsb** [comment]
2번으로 갑시당

**Comment by Hong-been** [comment]
leetcode/994.RottingOranges.js 형식으로 결정~!
